### ISSUE TITLE
Keeping connections to multiple local databases

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/MonetDBe-Python#75] opened 2020-07-07 20:00 UTC
**Describe the bug**
See the multiconnections.py example in the monetdbe-examples repositories.
It illustrates that the user should be able to keep multiple connections to the different database open.
It needs to be implemented.

**Software versions**
 - OS and version: [e.g. Ubuntu 18.04]
- Python version: [e.g. 3.7]
 - MonetDBe-Python version: [e.g. 0.7]

**Comment by gijzelaerr** [comment] 2020-09-11 08:00
duplicate of https://github.com/MonetDBSolutions/MonetDBe-Python/issues/5

**Closed by gijzelaerr** 2020-09-11 08:00 UTC
Labels: bug, duplicate, enhancement
